version: "3"
services:
  grpc-server:
    container_name: atoz_grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile
  grpc-client:
    container_name: atoz_grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    container_name: atoz_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - grpc-client:grpc-client
    depends_on:
      - grpc-server
      - grpc-client
